# Render blueprint for FragsHub backend
services:
  - type: web
    name: fragshub-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      # Add your env vars below (set actual values in Render UI for secrets)
      - key: CORS_ORIGIN
        value: https://fragshub-frontend-rgv41gwie-sarvesh-daymas-projects.vercel.app
      - key: FRONTEND_URL
        value: https://fragshub-frontend-rgv41gwie-sarvesh-daymas-projects.vercel.app
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CHALLONGE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
